### ISSUE TITLE
Custom Image Filenames

### ISSUE THREAD

**Issue by benbenbenbenbenben** [dcdc-io/taiko-screencheck#2]
Image filenames are currently in the format: <url><hash of selector descriptions>

We should:

1. Allow `{ path = "value" }` to override any internal logic.
2. Allow `{ path = function(taiko, etc){ return "value" } }` to override any internal logic.

@JamesTurnerGit ??

**Comment by JamesTurnerGit** [comment]
prefer 1 since it's closer to taiko's current solution

**Comment by benbenbenbenbenben** [comment]
Ha, it's not an either or, we'll have both.
